# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "mas-cli/tap"
tap "ojford/formulae"
tap "puppetlabs/puppet"

# Brew packages
brew "git-crypt"
brew "gnupg"
brew "mas"
brew "tmux"
brew "stow"
brew "httpie"
brew "ripgrep"
brew "loginitems"
brew "tree"
brew "pstree"
brew "htop"
brew "nmap"
brew "rename"
brew "wget"
brew "jq"
brew "lsd"
brew "youtube-dl"
brew "bat"
brew "visionmedia-watch"
brew "timewarrior"

# Casks
cask "1password"
cask "alfred"
cask "keepingyouawake"
cask "dash"
cask "iterm2-beta"
cask "bettertouchtool"
cask "grandperspective"
cask "joplin"
cask "menumeters"
cask "karabiner-elements"
cask "fugu"
cask "plex"
cask "mysides"
cask "nextcloud"
cask "airtame"
cask "gas-mask"
cask "font-hack-nerd-font"
cask "powershell"
cask "secretive"
cask "gfxcardstatus"
cask "safari-technology-preview"
cask "microsoft-edge"
cask "firefox-beta"
cask "activitywatch"
cask "google-drive"
cask "visual-studio-code"
cask "pe-client-tools"
cask "istat-menus"

# App Store
mas 'Microsoft Remote Desktop', id: 1295203466
mas 'Twitterrific', id: 1289378661
mas 'Bitwarden', id: 1352778147
mas '1Password for Safari', id: 1569813296
mas 'AmorphousDiskMark', id: 1168254295
