tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "caskroom/fonts"
tap "mas-cli/tap"
tap "ojford/formulae"
brew "git-crypt"
brew "gnupg"
brew "mas"
brew "tmux"
brew "stow"
brew "httpie"
brew "ripgrep"
brew "loginitems"
brew "dockutil"
brew "tree"
brew "jq"
cask "alfred"
cask "caffeine"
cask "dash"
cask "1password"
cask "iterm2"
cask "bettertouchtool"
cask "yujitach-menumeters"
cask "karabiner-elements"
cask "font-source-code-pro-for-powerline"
mas 'Microsoft Remote Desktop 10', id: 1295203466
mas 'Twitterrific', id: 1289378661
mas 'Todoist', id: 585829637
mas 'Slack', id: 803453959
