# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "mas-cli/tap"
tap "ojford/formulae"
tap "puppetlabs/puppet"

# Brew packages
brew "git-crypt"
brew "gnupg"
brew "mas"
brew "tmux"
brew "stow"
brew "httpie"
brew "ripgrep"
brew "loginitems"
brew "dockutil"
brew "tree"
brew "pstree"
brew "htop"
brew "nmap"
brew "wget"
brew "jq"
brew "python"
brew "ruby"
brew "golang"
brew "libav"
brew "lsd"
brew "postgresql"
brew "youtube-dl"

# Casks
cask "1password"
cask "alfred"
cask "keepingyouawake"
cask "dash"
cask "iterm2"
cask "bettertouchtool"
cask "grandperspective"
cask "joplin"
cask "menumeters"
cask "karabiner-elements"
cask "fugu"
cask "plex"
cask "mysides"
cask "nextcloud"
cask "airtame"
cask "gas-mask"
cask "font-hack-nerd-font"
cask "docker"
cask "powershell"

# App Store
mas 'Microsoft Remote Desktop 10', id: 1295203466
mas 'Twitterrific', id: 1289378661
mas 'BarTunes', id: 444425546
mas 'Trello', id: 1278508951
