#!/bin/sh

# This is probably not the best way to do this.
#   - We don't know if Karabiner.app is installed.
#   - We don't know if the options are in private.xml/loaded by app.

# Generated by /Applications/Karabiner.app/Contents/Library/bin/karabiner export

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set dfwarden_naga_side_button_8 1
/bin/echo -n .
$cli set remap.commandR2optionR 1
/bin/echo -n .
$cli set naga_side_button_1 1
/bin/echo -n .
$cli set naga_side_button_10 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_1 1
/bin/echo -n .
$cli set naga_side_button_7 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_10 1
/bin/echo -n .
$cli set naga_side_button_2 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_3 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_11 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_12 1
/bin/echo -n .
$cli set naga_side_button_8 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_5 1
/bin/echo -n .
$cli set naga_side_button_3 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_7 1
/bin/echo -n .
$cli set general.dont_remap_apple_keyboard 1
/bin/echo -n .
$cli set naga_side_button_11 1
/bin/echo -n .
$cli set naga_side_button_9 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_9 1
/bin/echo -n .
$cli set remap.optionL2commandL 1
/bin/echo -n .
$cli set naga_side_button_4 1
/bin/echo -n .
$cli set remap.optionrcommandr 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_2 1
/bin/echo -n .
$cli set naga_side_button_5 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_4 1
/bin/echo -n .
$cli set remap.commandL2optionL 1
/bin/echo -n .
$cli set naga_side_button_12 1
/bin/echo -n .
$cli set dfwarden_naga_side_button_6 1
/bin/echo -n .
$cli set naga_side_button_6 1
/bin/echo -n .
/bin/echo
