# Path to your oh-my-zsh configuration.
ZSH=$HOME/src/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# Warden: Nice fallback w/o powerline ZSH_THEME="dieter"
ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx brew brew-cask tmux virtualenv zsh-syntax-highlighting z)

source $ZSH/oh-my-zsh.sh

# Init boxen's env
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Homebrew zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

# Enable OpenSSL validation of certs
export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem

# Use Boxen's Caskroom
export HOMEBREW_CASK_OPTS="--caskroom=/usr/local/boxen-brewcask/Caskroom/"
